// wedding-site/src/components/Navigation.tsx
"use client";
import { useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

export default function Navigation() {
  const [isOpen, setIsOpen] = useState(false);
  const pathname = usePathname();

  const links = [
    { href: '/', label: 'Home' },
    { href: '/nav/schedule', label: 'Schedule' },
    { href: '/nav/travel', label: 'Travel' },
    { href: '/nav/wedding-party', label: 'Wedding Party' },
    { href: '/nav/registry', label: 'Registry' },
    { href: '/nav/gallery', label: 'Gallery' },
    { href: '/nav/faq', label: 'FAQ' },
  ];

  return (
    <nav className="flex flex-col items-center gap-4 w-full bg-primary text-secondary z-50 py-8 px-4 border-b border-gray-200 relative">
      <div className="text-3xl font-bold text-inherit font-serif">
        Jaime & Hank
      </div>
      
      <button 
        className="md:hidden text-2xl bg-none border-none cursor-pointer text-inherit"
        onClick={() => setIsOpen(!isOpen)}
      >
        ☰
      </button>

      <div className={`flex gap-8 transition-all duration-300 ${isOpen ? 'flex flex-col absolute top-full left-0 w-full bg-primary p-4 shadow-md' : 'hidden md:flex'}`}>
        {links.map((link) => (
          <Link 
            key={link.href}
            href={link.href}
            onClick={() => setIsOpen(false)}
            className={`
              relative pb-2 text-inherit no-underline transition-colors duration-300 font-sans
              after:content-[''] after:absolute after:bottom-0 after:left-0 after:h-[2px] after:bg-secondary after:transition-all after:duration-300
              hover:after:w-full
              ${pathname === link.href ? 'after:w-full' : 'after:w-0'}
            `}
          >
            {link.label}
          </Link>
        ))}
      </div>
    </nav>
  );
}

// src/components/Navigation.vue
<template>
    <div class="navigation">
        <div class="nav-title">Jaime & Hank</div>
        <button class="menu-toggle" @click="isOpen = !isOpen">
            ☰
        </button>
        <div class="nav-links" :class="{ active: isOpen }">
            <RouterLink to="/" @click="isOpen = false">Home</RouterLink>
            <RouterLink to="/schedule" @click="isOpen = false">Schedule</RouterLink>
            <RouterLink to="/travel" @click="isOpen = false">Travel</RouterLink>
            <RouterLink to="/wedding-party" @click="isOpen = false">Wedding Party</RouterLink>
            <RouterLink to="/registry" @click="isOpen = false">Registry</RouterLink>
            <RouterLink to="/gallery" @click="isOpen = false">Gallery</RouterLink>
            <RouterLink to="/faq" @click="isOpen = false">FAQ</RouterLink>
        </div>
    </div>
</template>

<script setup>
  import { ref } from 'vue'
  import { RouterLink } from 'vue-router'

  const isOpen = ref(false)
</script>

<style scoped>
.navigation {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
  top: 0;
  width: 100%;
  background-color: #f5f5f5;
  z-index: 100;
  padding: 2rem 1rem;
  border-bottom: 1px solid #ddd;
}

.nav-title {
  font-size: 2rem;
  font-weight: bold;
  color: #e91e63;
  font-family: 'Georgia', serif;
}

.menu-toggle {
  display: none;
  background: none;
  border: none;
  font-size: 1.5rem;
  cursor: pointer;
}

.nav-links {
  display: flex;
  gap: 2rem;
}

a {
  text-decoration: none;
  color: inherit;
  position: relative;
  padding-bottom: 0.5rem;
  transition: color 0.3s ease;
  font-family: 'Trebuchet MS', sans-serif;

}

a::after {
  content: '';
  position: absolute;
  bottom: 0;
  left: 0;
  width: 0;
  height: 2px;
  background-color: #e91e63;
  transition: width 0.3s ease;
}

a:hover::after {
  width: 100%;
}

a.router-link-active::after {
  width: 100%;
  background-color: #e91e63;
}

@media (max-width: 768px) {
  .navigation {
    position: relative;
    flex-direction: row;
    justify-content: space-between;
    padding: 1rem;
  }

  .nav-title {
    font-size: 1.2rem;
  }

  .menu-toggle {
    display: block;
  }

  .nav-links {
    flex-direction: column;
    gap: 0;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.3s ease;
    position: absolute;
    top: 100%;
    left: 0;
    width: 100%;
    background-color: #f5f5f5;
    z-index: 100;
  }

  .nav-links.active {
    max-height: 500px;
  }

  a {
    padding: 1rem;
    border-bottom: 1px solid #e0e0e0;
    display: block;
  }

  a::after {
    display: none;
  }

  a.router-link-active {
    background-color: #ffe0e6;
  }
}
</style>
